
fn main()
{
	try{
		throw "catch";
	}catch(ex){
		return ex;
	}
}